create table if not exists public.shift_position_logs (
  id bigint generated by default as identity primary key,
  shift_id bigint not null references public.shifts(id) on delete cascade,
  ats_unit_id bigint not null references public.ats_units(id) on delete cascade,
  user_id uuid not null references public.profiles(id) on delete restrict,
  recorded_by uuid references public.profiles(id) on delete set null,
  entered_at_utc timestamptz not null default now(),
  left_at_utc timestamptz,
  notes text,
  created_at timestamptz not null default now(),
  constraint shift_position_logs_exit_after_entry
    check (left_at_utc is null or left_at_utc >= entered_at_utc)
);

create index if not exists shift_position_logs_shift_id_idx
  on public.shift_position_logs (shift_id, entered_at_utc);

grant select, insert, update on public.shift_position_logs to authenticated;
grant usage, select on sequence public.shift_position_logs_id_seq to authenticated;

alter table public.shift_position_logs enable row level security;

drop policy if exists "shift_position_logs_select_same_unit" on public.shift_position_logs;
create policy "shift_position_logs_select_same_unit"
  on public.shift_position_logs
  for select
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.ats_unit_id = shift_position_logs.ats_unit_id
    )
  );

drop policy if exists "shift_position_logs_insert_same_unit" on public.shift_position_logs;
create policy "shift_position_logs_insert_same_unit"
  on public.shift_position_logs
  for insert
  to authenticated
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.ats_unit_id = shift_position_logs.ats_unit_id
    )
    and recorded_by = auth.uid()
  );

drop policy if exists "shift_position_logs_update_same_unit" on public.shift_position_logs;
create policy "shift_position_logs_update_same_unit"
  on public.shift_position_logs
  for update
  to authenticated
  using (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.ats_unit_id = shift_position_logs.ats_unit_id
    )
  )
  with check (
    exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.ats_unit_id = shift_position_logs.ats_unit_id
    )
  );
